version: "3"

tasks:
  setup:
    desc: Setup development environment
    cmds:
      - uv sync --group dev --group test
      - uv run pre-commit install
    sources:
      - pyproject.toml
      - uv.lock
      - .pre-commit-config.yaml

  lint:
    desc: Run linting checks
    cmds:
      - uv run pre-commit run --all-files

  test:
    desc: Run all tests
    cmds:
      - uv sync --group test
      - uv run playwright install --with-deps
      - uv run pytest

  build:
    desc: Build the package
    cmds:
      - cd streamlit_folium/frontend/ && npm install && npm run build
      - uv build

  run-frontend:
    desc: Run the frontend for development
    dir: streamlit_folium/frontend/
    cmds:
      - npm install
      - npm run start

  test-frontend:
    desc: Run frontend and tests in parallel
    cmds:
      - task --parallel run-frontend test

  run-streamlit:
    desc: Run streamlit example app
    cmds:
      - uv run streamlit run examples/streamlit_app.py

  generate-tests:
    desc: Generate playwright tests
    cmds:
      - task --parallel _run-streamlit _run-playwright

  _run-streamlit:
    internal: true
    cmds:
      - uv run streamlit run examples/streamlit_app.py --server.port 8599 --server.headless true

  _run-playwright:
    internal: true
    cmds:
      - uv run playwright codegen localhost:8599 --target=python-pytest