version: "3"

tasks:
  install-pre-commit:
    desc: Install pre-commit hooks
    cmds:
      - uv add pre-commit --dev
      - uv run pre-commit install
    sources:
      - .pre-commit-config.yaml

  install-package:
    desc: Install the package
    cmds:
      - uv sync
    sources:
      - pyproject.toml
      - uv.lock

  install-test-deps:
    desc: Install the dependencies for testing
    cmds:
      - uv sync --group dev --group test
      - uv run playwright install --with-deps
    sources:
      - pyproject.toml

  lint:
    desc: Run linting checks
    deps:
      - install-pre-commit
    cmds:
      - uv run pre-commit run --all-files

  test:
    desc: Run all tests
    deps:
      - install-test-deps
    cmds:
      - uv run pytest

  test-frontend:
    cmds:
      - task --parallel run-frontend test

  run-frontend:
    desc: Run the frontend for testing purposes
    dir: streamlit_folium/frontend/
    cmds:
      - npm install
      - npm run start

  _run-streamlit: uv run streamlit run examples/streamlit_app.py --server.port 8599 --server.headless true

  _run-playwright: uv run playwright codegen localhost:8599 --target=python-pytest

  generate-tests:
    desc: Generate tests for the frontend
    cmds:
      - task --parallel _run-streamlit _run-playwright

  generate-tests-frontend:
    desc: Generate tests for the frontend
    cmds:
      - task --parallel run-frontend _run-streamlit _run-playwright
