# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: install node
      uses: actions/setup-node@v3
      with:
          node-version: 20
#       run: |
#         sudo apt install nodejs npm
#         npm --version
    - name: build streamlit-folium JS
      run: |
        cd streamlit_folium/frontend/
        npm install
        npm run build
    - name: Build and publish
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pwd
        uv build
        uv publish
